name: Deploy to Render
on: { workflow_dispatch: {}, push: { branches: ["main"] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify secrets exist
      shell: bash
      run: |
        test -n "${{ secrets.RENDER_API_KEY }}" || (echo "Missing RENDER_API_KEY" && exit 1)
        test -n "${{ secrets.RENDER_SERVICE_ID }}" || (echo "Missing RENDER_SERVICE_ID" && exit 1)

    - name: Trigger Render deploy
      shell: bash
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        set -euo pipefail
        curl -fsS -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
          -d '{}' -o /tmp/resp.json
        echo "Render response:"
        cat /tmp/resp.json
